apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-agent
  template:
    metadata:
      labels:
        app: astro-agent
    spec:
      containers:
        - name: astro-agent
          image: asia-south1-docker.pkg.dev/astro-ai-agent-470310/astro-ai-agent-repo/astro-ai-agent-app:v1 # we will override this in github actionwith latest version
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: astro-secret
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/pubsub-key/key.json
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "1Gi"
          volumeMounts:
            - name: pubsub-key
              mountPath: /secrets/pubsub-key
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 60
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/db
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 120
            failureThreshold: 5
      volumes:
        - name: pubsub-key
          secret:
            secretName: pubsub-key
