apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-agent
  template:
    metadata:
      labels:
        app: astro-agent
    spec:
      containers:
        - name: astro-agent
          image: asia-south1-docker.pkg.dev/astro-ai-agent-1/astro-ai-agent-repo/astro-ai-agent-app:v1 # we will override this in github actionwith latest version
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: astro-secret
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/db
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
