apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astro-agent-ingress
spec:
  ingressClassName: gce
  rules:
  - host: astroapp.nononsensedev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: astro-agent-service
            port:
              number: 80
