apiVersion: v1
kind: Service
metadata:
  name: astro-agent-service
spec:
  type: NodePort
  selector:
    app: astro-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080